//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuxuryWebV1.Models
{
    public partial class Account
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public int IDRole { get; set; }
        public int IDStaff { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
