//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuxuryWebV1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LuxuryDBv3Entities : DbContext
    {
        public LuxuryDBv3Entities()
            : base("name=LuxuryDBv3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<HairServices> HairServices { get; set; }
        public virtual DbSet<MakeSteps> MakeSteps { get; set; }
        public virtual DbSet<OrderIncomes> OrderIncomes { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Revenue> Revenue { get; set; }
        public virtual DbSet<RevenueType> RevenueType { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Balance> Balance { get; set; }
    }
}
