//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuxuryWebV1.Models
{
    public partial class OrderIncomes
    {
        public double TotalPrice { get; set; }
        public int IDSvc { get; set; }
        public int IDOrder { get; set; }
    
        public virtual HairServices HairServices { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
