//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuxuryWebV1.Models
{
    public partial class Revenue
    {
        public int IDRevenue { get; set; }
        public string Title { get; set; }
        public double Amount { get; set; }
        public string Note { get; set; }
        public double DateAccessed { get; set; }
        public int IDType { get; set; }
        public int IDStaff { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual RevenueType RevenueType { get; set; }
    }
}
